/**
 * Emits src/generated/covers.ts with each cover's intrinsic pixel dimensions.
 *
 * §10 requires explicit width/height on every image so it reserves its space and cannot
 * shift layout while loading. Hardcoding one size for all covers is wrong the moment the
 * owner supplies files with different aspect ratios — which they did: the readmissions
 * figure is a wide three-panel export, the EER diagram is near-4:3. Reading the real
 * header here keeps the attributes honest without shipping an image library.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dir = resolve(root, 'src/content/covers')

/** PNG: IHDR width/height sit at fixed offsets right after the 8-byte signature. */
function pngSize(buf) {
  if (buf.length < 24) return null
  if (buf[0] !== 0x89 || buf[1] !== 0x50) return null
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) }
}

/** JPEG: walk the marker segments to the first SOF (frame header) and read its size. */
function jpegSize(buf) {
  if (buf[0] !== 0xff || buf[1] !== 0xd8) return null
  let offset = 2
  while (offset < buf.length - 9) {
    if (buf[offset] !== 0xff) {
      offset += 1
      continue
    }
    const marker = buf[offset + 1]
    // SOF0–SOF15, excluding DHT (c4), DAC (cc) and the RSTn markers.
    const isSOF = marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc
    if (isSOF) {
      return { height: buf.readUInt16BE(offset + 5), width: buf.readUInt16BE(offset + 7) }
    }
    offset += 2 + buf.readUInt16BE(offset + 2)
  }
  return null
}

const entries = []
for (const file of readdirSync(dir).sort()) {
  if (!/\.(png|jpe?g)$/i.test(file)) continue
  const buf = readFileSync(resolve(dir, file))
  const size = file.toLowerCase().endsWith('.png') ? pngSize(buf) : jpegSize(buf)
  if (!size) {
    throw new Error(`[gen-covers] could not read dimensions for ${file}`)
  }
  entries.push({ file, ...size })
}

const out = resolve(root, 'src/generated/covers.ts')
mkdirSync(dirname(out), { recursive: true })
writeFileSync(
  out,
  `// GENERATED by scripts/gen-covers.mjs — do not edit.\n` +
    `export interface CoverSize { width: number; height: number }\n` +
    `export const COVER_SIZES: Record<string, CoverSize> = ${JSON.stringify(
      Object.fromEntries(entries.map((e) => [e.file, { width: e.width, height: e.height }])),
      null,
      2,
    )}\n`,
  'utf8',
)

console.log(
  `[gen-covers] ${entries.length} cover(s): ${entries.map((e) => `${e.file} ${e.width}×${e.height}`).join(', ')}`,
)
