/**
 * Generates the single source of truth for the app version, derived from package.json.
 *
 * Why a generated module rather than Vite's `define`: the Worker is bundled by wrangler
 * (esbuild), which never sees vite.config.ts. A `define` there works in the client and
 * throws "__APP_VERSION__ is not defined" at the edge. A generated .ts module is imported
 * normally by both bundlers, so client and Worker cannot drift apart.
 *
 * Emits:
 *   src/generated/version.ts  — imported by client + worker
 *   public/version.json       — fetched at runtime to detect a stale cached build
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'))
const version = pkg.version
const buildTime = process.env.BUILD_TIME ?? new Date().toISOString()

const tsPath = resolve(root, 'src/generated/version.ts')
mkdirSync(dirname(tsPath), { recursive: true })
writeFileSync(
  tsPath,
  `// GENERATED by scripts/gen-version.mjs — do not edit.\n` +
    `// Source of truth is the "version" field in package.json.\n` +
    `export const APP_VERSION = ${JSON.stringify(version)}\n` +
    `export const BUILD_TIME = ${JSON.stringify(buildTime)}\n`,
  'utf8',
)

const jsonPath = resolve(root, 'public/version.json')
mkdirSync(dirname(jsonPath), { recursive: true })
writeFileSync(jsonPath, `${JSON.stringify({ version, buildTime }, null, 2)}\n`, 'utf8')

console.log(`[gen-version] v${version} (${buildTime})`)
